@startuml
abstract Instrumento {
-{field} nombre: String
-{field} material: String
+{method} Instrumento(nombre: String, material: String)
+{method} getNombre(): String
+{method} getMaterial(): String
}
class Cuerda {
-{field} tipoCuerda: String
-{field} n_cuerdas: int
-{field} tipo: String
+{method} Cuerda(nombre: String, material, String,\ntipoCuerda: String, n_cuerdas: int,\ntipo: String)
+{method} getTipoCuerda(): String
+{method} getN°cuerdas(): INT
+{method} getTipo(): String
}
class Percusion {
-{field} tipoPercusion: String
-{field} altura: float
+{method} Percusion(nombre: String, material: String,\ntipoPercusion: String, altura: float)
+{method} getTipoPercusion(): String
+{method} getAltura(): float
}
class Viento {
+{method} Viento(nombre: String, material: String)
}
class ListaInstrumentos {
-{field} max: int
-{field} tamanio: int
-{field} Instrumento ListaInstrumentos[]
+{method} ListaInstrumentos(max: int)
+{method} agregarInstrumento(Instrumento instrumento)
+{method} buscarInstrumento(Instrumento instrumento)
+{method} eliminarInstrumento(Instrumento instrumento)
}
interface Sistema {
+{field} agregarInstrumento(): void
+{field} venderInstrumento(): void
+{field} consultarInventario(): void
}
class SistemaImpl {
}
Sistema "1  " <|.. "1  " SistemaImpl
Cuerda  --|>  Instrumento
Percusion  --|>  Instrumento
Viento  --|>  Instrumento
SistemaImpl "1" --> "1   " ListaInstrumentos : Administra
Instrumento "*" --o "1" ListaInstrumentos : Almacena


@enduml