@startuml

entity BeathTheRythm{
Instrumentos
}

entity SistemaInventario{
Interfaz
}

entity Instrumento{
Nombre
Material
Codigo
Precio
Stock
TipoInstrumento
}

BeathTheRythm "1" -> "0..*      " Instrumento : posee
BeathTheRythm -> SistemaInventario: tiene
SistemaInventario "1" -> "0..*" Instrumento : administra
@enduml